### ISSUE TITLE
[BUG] 启动ExampleSite报错

### ISSUE THREAD

**Issue by zcharym** [dillonzq/LoveIt#541] opened 2020-10-27 13:52 UTC
`ERROR 2020/10/27 21:49:42 Failed to get JSON resource "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=1": Get "https://api.instagram.com/oembed/?url=https://instagram.com/p/BWNjjyYFxVx/&hidecaption=1": dial tcp 208.77.47.172:443: i/o timeout`
![image](https://user-images.githubusercontent.com/57801678/97310848-ae1d7e80-189e-11eb-84d8-1a97ab148c86.png)

**Comment by nekr0z** [comment] 2020-10-27 13:57
Duplicate of #518

**Comment by Zach-Ma** [comment] 2020-10-27 14:06
Thanks for reminding me.`

**Closed** 2022-08-30 10:14 UTC
Labels: bug
